name: Security Audit

on:
  push:
    paths:
      - '**/Cargo.toml'
  schedule:
    - cron: '0 0 * * *'

jobs:
  cargo_audit:
    name: "Cargo Audit"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Generate Cargo.lock
        run: cargo generate-lockfile
      - name: Run Cargo Audit
        uses: rustsec/audit-check@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      issues: write
      checks: write
